Serialization fix
tomfun/BranderEAVBundle pull request #12
Opened 2017-04-07 15:42 UTC by mom666

#11

2017-04-07 17:30 UTC, tomfun requested changes

2017-04-07 17:30 UTC, tomfun commented on src/Controller/RestPublicController.php
> -            if (!$this->securityChecker->isGranted(
No, left security unchanged, manage still affect http cache

2017-04-07 17:30 UTC, tomfun commented on src/Controller/RestPublicController.php
> +        $cxt = SerializationContext::create();
If no manage flag do we need *Default* group?

2017-04-10 09:43 UTC, mom666 commented on src/Controller/RestPublicController.php
> +        $cxt = SerializationContext::create();
Done

2017-04-10 10:37 UTC, merged